import Head from "next/head";

import styles from "../styles/Home.module.scss";
import Layout from "../Components/Layout";
import Link from "next/link";
import { Menu } from "../Components/Menu";

export default function Home() {
  return (
    <Layout title="" keywords="" description="">
      <Head>
        <title>Fit board financial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className={styles.main}></main>
    </Layout>
  );
}
